### ISSUE TITLE
renaming of to_item kwarg

### ISSUE THREAD

**Issue by SimonKvantdator** [AndreiChertkov/teneva#5]
```
>>> teneva.__version__
'0.14.7'
```
In order to use svd_incomplete, I had to change line 192 in `svd.py` from
```
        M = np.array([teneva.get(Y_res[:mode], i, to_item=False)
```
to
```
        M = np.array([teneva.get(Y_res[:mode], i, _to_item=False)
```

**Comment by AndreiChertkov** [comment]
Dear @SimonKvantdator , thank you very much for noticing this!

We have made a corresponding correction in the new version 0.14.8 that has just been released. I am closing this issue.
